# -*- coding: utf-8 -*-
"""Swimming School.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q7H_YV3i-GxOZRhshLuvlGrEIEj-kBTc

# New section

# Tasks 
## This the list of stuff to do


1.   Drop duplicate columns 
2.   Figure out how to plot the LSOA and colour code them based on delta values
3.   Look into only keeping the areas with **biggest** change
4.  Figure out whether +/-1000 means an area is more or less affordable than it was.
5. Find and save a link to IMD documentation somewhere here.
6. figure out a nice folder structure and load the variables with it.
7. Find median house price by LSOA/MSOA 2019/15 datasets.
"""

!wget -O IMD_2015.csv https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/467774/File_7_ID_2015_All_ranks__deciles_and_scores_for_the_Indices_of_Deprivation__and_population_denominators.csv
!wget -O IMD_2019.csv https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/845345/File_7_-_All_IoD2019_Scores__Ranks__Deciles_and_Population_Denominators_3.csv
!wget -O LSOA.zip https://data.cambridgeshireinsight.org.uk/sites/default/files/Lower_Layer_Super_Output_Areas_December_2011_Generalised_Clipped__Boundaries_in_England_and_Wales.zip

import pandas as pd
#read csvs
imd_2015 = pd.read_csv("IMD_2015.csv")
imd_2019 = pd.read_csv("IMD_2019.csv")

#sort pandas
imd_2015 = imd_2015.sort_values(by=['LSOA code (2011)'], ignore_index=True)
imd_2019 = imd_2019.sort_values(by=['LSOA code (2011)'], ignore_index=True)

#grab just area codes and names
names_codes = imd_2019[["LSOA code (2011)","LSOA name (2011)"]]

#finding the difference
delta_housing_barriers =  imd_2019["Barriers to Housing and Services Rank (where 1 is most deprived)"] - imd_2015["Barriers to Housing and Services Rank (where 1 is most deprived)"]

names_codes["delta_housing_barriers"] = delta_housing_barriers

names_codes.rename({"LSOA code (2011)":"lsoa11cd"}, axis=1, inplace=True)
names_codes.head()

"""# PLOTTING ON A GRAPH, COLOUR CODING BY DIFFERENCE"""

!pip install geopandas

!unzip LSOA.zip

import geopandas as gp
LSOA = gp.read_file("Lower_Layer_Super_Output_Areas_December_2011_Generalised_Clipped__Boundaries_in_England_and_Wales.shp")

LSOA.plot()

LSOA.sort_values(by=["lsoa11cd"], ignore_index=True)

LSOA = LSOA.merge(names_codes, on='lsoa11cd')

LSOA.head()

